### ISSUE TITLE
mod_aws doesn't work after kill -HUP to reload config

### ISSUE THREAD

**Issue by 3dw1n** [Castaglia/proftpd-mod_aws#41]
### Problem
With the very minimal **proftpd.conf-tiny** shown below configuring an ftp-server on port 21 with mod_aws loaded enabling only the AWSHealthCheck for testing purposes (doesn't matter if more mod_aws functionality is enabled) mod_aws doesn't seem to reload when sending SIGHUP to the controlling proftpd process running as a daemon.

### proftpd starts up correctly:

```
#/testing/proftpd/sbin/proftpd -d 9 -c /testing/proftpd/etc/proftpd.conf-tiny
2023-04-18 11:40:55,493 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209]: using TCP receive buffer size of 131072 bytes
2023-04-18 11:40:55,493 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209]: using TCP send buffer size of 20480 bytes
2023-04-18 11:40:55,504 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209]: disabling runtime support for IPv6 connections
2023-04-18 11:40:55,504 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209]: mod_dso/0.5: loading 'mod_aws.c'
2023-04-18 11:40:55,511 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209]: mod_dso/0.5: loaded module 'mod_aws' (from '/testing/builds/proftpd-1.3.8/libexec/mod_aws.so', last modified on Mon Mar 20 10:42:13 2023)
2023-04-18 11:40:55,511 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209]: mod_aws/0.0: libcurl version: 7.88.1
2023-04-18 11:40:55,511 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209]: mod_aws/0.0: libcurl compiled using OpenSSL version: OpenSSL/3.0.8
2023-04-18 11:40:55,513 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209]: ROOT PRIVS at mod_auth_file.c:1683
2023-04-18 11:40:55,513 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209]: RELINQUISH PRIVS at mod_auth_file.c:1686
2023-04-18 11:40:55,513 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209]: ROOT PRIVS at mod_auth_file.c:1822
2023-04-18 11:40:55,514 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209]: RELINQUISH PRIVS at mod_auth_file.c:1825
2023-04-18 11:40:55,521 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal:
2023-04-18 11:40:55,521 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: Config for ProFTPD:
2023-04-18 11:40:55,521 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: Port
2023-04-18 11:40:55,521 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: DefaultServer
2023-04-18 11:40:55,521 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: PassivePorts
2023-04-18 11:40:55,521 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: Umask
2023-04-18 11:40:55,521 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: RootLogin
2023-04-18 11:40:55,521 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: DefaultRoot
2023-04-18 11:40:55,521 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: RequireValidShell
2023-04-18 11:40:55,521 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: UserID
2023-04-18 11:40:55,521 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: UserName
2023-04-18 11:40:55,521 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: GroupID
2023-04-18 11:40:55,521 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: GroupName
2023-04-18 11:40:55,521 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: AuthOrder
2023-04-18 11:40:55,521 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: AuthGroupFile
2023-04-18 11:40:55,521 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: AuthUserFile
2023-04-18 11:40:55,521 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: ROOT PRIVS at mod_ctrls.c:1233
2023-04-18 11:40:55,531 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: RELINQUISH PRIVS at mod_ctrls.c:1235
2023-04-18 11:40:55,531 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: ROOT PRIVS at mod_delay.c:583
2023-04-18 11:40:55,531 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: RELINQUISH PRIVS at mod_delay.c:586
2023-04-18 11:40:55,532 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: ROOT PRIVS at mod_rlimit.c:554
2023-04-18 11:40:55,532 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: RELINQUISH PRIVS at mod_rlimit.c:557
2023-04-18 11:40:55,532 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: set core resource limits for daemon
2023-04-18 11:40:55,532 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: ignoring supplemental groups for non-root UID 65534
2023-04-18 11:40:55,532 ip-1-2-3-4.eu-west-1.compute.internal proftpd[3819209] ip-1-2-3-4.eu-west-1.compute.internal: SETUP PRIVS at main.c:2770

```
Then I'm able to telnet to the AWSHealthCheck port on 1234:

```
#telnet 1.2.3.4 1234
Trying 1.2.3.4...
Connected to 1.2.3.4.
Escape character is '^]'.
^]
telnet> quit
Connection closed.

```
Now when I tell proftpd to reload it's config
`#killall -HUP proftpd`

Telnet to port 1234 doesn't work anymore
```
#telnet 1.2.3.4 1234
Trying 1.2.3.4...
telnet: connect to address 1.2.3.4: Connection refused

```

When other functionality of mod_aws is enabled it also stops working after a SIGHUP.

When I run proftpd with --nodaemon mod_aws does reload on a kill -HUP, so it's only a problem when running as daemon.

### proftpd.config-tiny:

```
ServerType          standalone
UseIPv6             off
PidFile             /testing/proftpd/var/proftpd-%{env:MB_FTPHOST}.pid
Port                21
DefaultServer       on

LoadModule          mod_aws.c

AWSEngine           on
AWSLog              /testing/proftpd/var/log/aws-%{env:MB_FTPHOST}.log
AWSHealthCheck      "/health" %{env:HOSTNAME} 1234

PassivePorts          60000 65534
Umask                 002
RootLogin             off
DefaultRoot           ~
RequireValidShell     off
User                  nobody
Group                 nobody
AuthOrder             mod_auth_file.c
AuthGroupFile         /testing/proftpd/etc/proftpd.group id 2000-4000 name ^testing$
AuthUserFile          /testing/proftpd/etc/proftpd.passwd home ^/testing/ftproot/
```

### proftpd -V

```
Compile-time Settings:
  Version: 1.3.8 (stable)
  Platform: LINUX [Linux 6.1.19-30.43.amzn2023.x86_64 x86_64]
  OS/Release:
    NAME="Amazon Linux"
    VERSION="2023"
    ID="amzn"
    ID_LIKE="fedora"
    VERSION_ID="2023"
    PLATFORM_ID="platform:al2023"
    PRETTY_NAME="Amazon Linux 2023"
    CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
    SUPPORT_END="2028-03-01"
  Built: Mon Mar 20 2023 10:39:53 UTC
  Built With:
    configure  '--prefix=/testing/builds/proftpd-1.3.8' '--sysconfdir=/testing/proftpd/etc' '--localstatedir=/testing/proftpd/var' '--enable-ctrls' '--enable-dso' '--with-shared=mod_exec:mod_aws:mod_ctrls_admin:mod_sftp:mod_tls:mod_rewrite:mod_sql:mod_sql_mysql:mod_sftp_sql:mod_ban:mod_ifsession:mod_proxy_protocol' '--with-includes=/usr/include/mysql:/usr/include/curl:/usr/include/libxml2:/usr/include/openssl:/testing/builds/libsodium/include' '--with-libraries=/usr/lib64:/usr/local/lib:/testing/builds/libsodium/lib' '--enable-sodium'

  CFLAGS: -g2 -O2 -Wall -fno-omit-frame-pointer -fno-strict-aliasing -Werror=implicit-function-declaration
  LDFLAGS: -Wl,-L$(top_srcdir)/lib,-L$(top_builddir)/lib  -rdynamic -L/testing/builds/libsodium/lib -L/usr/local/lib -L/usr/lib64 -L/usr/lib64/
  LIBS:  -lssl -lcrypto -lsodium -lresolv -lresolv -lcrypt  -pthread

  Files:
    Configuration File:
      /testing/proftpd/etc/proftpd.conf
    Pid File:
      /testing/proftpd/var/proftpd.pid
    Scoreboard File:
      /testing/proftpd/var/proftpd.scoreboard
    Header Directory:
      /testing/builds/proftpd-1.3.8/include/proftpd
    Shared Module Directory:
      /testing/builds/proftpd-1.3.8/libexec

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    + Controls support
    - curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    - ncurses support
    - NLS support
    + OpenSSL support (OpenSSL 3.0.5 5 Jul 2022)
    - PCRE support
    - PCRE2 support
    - POSIX ACL support
    - Redis support
    + Sendfile support
    + Shadow file support
    + Sodium support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

**Comment by 3dw1n** [comment]
Just noticed the following in the logfile:

```
2023-04-20 10:43:06,442 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2314082] ip-1-2-3-4.eu-west-1.compute.internal: received SIGHUP -- master server reparsing configuration file
2023-04-20 10:43:06,446 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2314082] ip-1-2-3-4.eu-west-1.compute.internal: ROOT PRIVS at mod_aws.c:664
2023-04-20 10:43:06,447 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2314082] ip-1-2-3-4.eu-west-1.compute.internal: RELINQUISH PRIVS at mod_aws.c:667
2023-04-20 10:43:06,447 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2314082] ip-1-2-3-4.eu-west-1.compute.internal: mod_dso/0.5: unloading 'mod_aws.c'
```
mod_aws gets unloaded: **mod_dso/0.5: unloading 'mod_aws.c'** Why?

and here's the tracelog with event:99 set only:

```
2023-04-20 10:51:32,211 [2325126] <event:3>: module 'aws' (0x7f7575b20840) registering handler for event 'core.exit' (at 0x7f7575b0ca60)
2023-04-20 10:51:32,211 [2325126] <event:3>: module 'ctrls' (0x4ec460) unregistering handler for event 'core.restart'
2023-04-20 10:51:32,211 [2325126] <event:3>: module 'dso' (0x4ec220) unregistering handler for event 'core.restart'
2023-04-20 10:51:32,211 [2325126] <event:3>: module 'facts' (0x4ec080) registering handler for event 'core.session-reinit' (at 0x499150)
2023-04-20 10:51:32,211 [2325126] <event:3>: module 'delay' (0x4ebde0) registering handler for event 'core.session-reinit' (at 0x4980b0)
2023-04-20 10:51:32,212 [2325126] <event:3>: module 'log' (0x4eb9c0) registering handler for event 'core.session-reinit' (at 0x491f60)
2023-04-20 10:51:32,222 [2325126] <event:3>: module 'log' (0x4eb9c0) registering handler for event 'core.exit' (at 0x491770)
2023-04-20 10:51:32,222 [2325126] <event:3>: module 'log' (0x4eb9c0) registering handler for event 'core.timeout-stalled' (at 0x4936c0)
2023-04-20 10:51:32,222 [2325126] <event:3>: module 'auth' (0x4eb460) registering handler for event 'core.session-reinit' (at 0x488400)
2023-04-20 10:51:32,238 [2325126] <event:3>: module 'auth' (0x4eb460) registering handler for event 'core.exit' (at 0x482ff0)
2023-04-20 10:51:32,279 [2325126] <event:3>: module 'auth_file' (0x4eae40) registering handler for event 'core.session-reinit' (at 0x480d70)
2023-04-20 10:51:32,279 [2325126] <event:3>: module 'auth_unix' (0x4eab40) registering handler for event 'core.exit' (at 0x47e4a0)
2023-04-20 10:51:32,279 [2325126] <event:3>: module 'auth_unix' (0x4eab40) registering handler for event 'core.session-reinit' (at 0x47ee30)
2023-04-20 10:51:32,279 [2325126] <event:3>: module 'rlimit' (0x4ea820) registering handler for event 'core.chroot' (at 0x47cdf0)
2023-04-20 10:51:32,279 [2325126] <event:3>: module 'xfer' (0x4ea6c0) registering handler for event 'core.exit' (at 0x47bd20)
2023-04-20 10:51:32,279 [2325126] <event:3>: module 'xfer' (0x4ea6c0) registering handler for event 'core.session-reinit' (at 0x4754a0)
2023-04-20 10:51:32,279 [2325126] <event:3>: module 'xfer' (0x4ea6c0) registering handler for event 'core.signal.USR2' (at 0x47b310)
2023-04-20 10:51:32,279 [2325126] <event:3>: module 'xfer' (0x4ea6c0) registering handler for event 'core.timeout-session' (at 0x47bc80)
2023-04-20 10:51:32,279 [2325126] <event:3>: module 'xfer' (0x4ea6c0) registering handler for event 'core.timeout-stalled' (at 0x47bbd0)
2023-04-20 10:51:32,279 [2325126] <event:8>: dispatching event 'core.connected' to mod_core (at 0x466260, use cache = false)
2023-04-20 10:51:32,291 [2325126] <event:8>: dispatching event 'core.exit' to mod_xfer (at 0x47bd20, use cache = false)
2023-04-20 10:51:32,291 [2325126] <event:8>: dispatching event 'core.exit' to mod_auth_unix (at 0x47e4a0, use cache = false)
2023-04-20 10:51:32,291 [2325126] <event:8>: dispatching event 'core.exit' to mod_auth (at 0x482ff0, use cache = false)
2023-04-20 10:51:32,292 [2325126] <event:8>: dispatching event 'core.exit' to mod_log (at 0x491770, use cache = false)
2023-04-20 10:51:32,292 [2325126] <event:8>: dispatching event 'core.exit' to mod_aws (at 0x7f7575b0ca60, use cache = false)
2023-04-20 10:51:32,292 [2325126] <event:8>: dispatching event 'core.exit' to core (at 0x41f4a0, use cache = false)
2023-04-20 10:51:34,916 [2324809] <event:8>: dispatching event 'core.restart' to mod_aws (at 0x7f7575b0d4b0, use cache = false)
2023-04-20 10:51:34,926 [2324809] <event:8>: dispatching event 'core.restart' to mod_ctrls (at 0x49e950, use cache = false)
2023-04-20 10:51:34,926 [2324809] <event:8>: dispatching event 'core.restart' to mod_dso (at 0x49c1b0, use cache = false)
2023-04-20 10:51:34,926 [2324809] <event:8>: dispatching event 'core.module-unload' to mod_aws (at 0x7f7575b0d650, use cache = false)
2023-04-20 10:51:34,926 [2324809] <event:3>: module 'aws' (0x7f7575b20840) unregistering handler for event '(all)'
```

And with `proftpd -d 9 -nd10 -c proftpd.conf-tiny` logging stops after sending SIGHUP

```
2023-04-20 11:08:14,156 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2345842] ip-1-2-3-4.eu-west-1.compute.internal: RELINQUISH PRIVS at mod_ctrls.c:753
2023-04-20 11:08:14,397 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2345842] ip-1-2-3-4.eu-west-1.compute.internal: received SIGHUP -- master server reparsing configuration file
2023-04-20 11:08:14,402 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2345842] ip-1-2-3-4.eu-west-1.compute.internal: ROOT PRIVS at mod_aws.c:664
2023-04-20 11:08:14,403 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2345842] ip-1-2-3-4.eu-west-1.compute.internal: RELINQUISH PRIVS at mod_aws.c:667
2023-04-20 11:08:14,403 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2345842] ip-1-2-3-4.eu-west-1.compute.internal: mod_dso/0.5: unloading 'mod_aws.c'
```

Sending SIGHUP again doesn't do anything, after sending SIGKILL the following gets logged before exit:

```
2023-04-20 11:09:38,799 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2345842] ip-1-2-3-4.eu-west-1.compute.internal: ProFTPD killed (signal 2)
2023-04-20 11:09:38,799 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2345842] ip-1-2-3-4.eu-west-1.compute.internal: ROOT PRIVS at signals.c:59
2023-04-20 11:09:38,804 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2345842] ip-1-2-3-4.eu-west-1.compute.internal: ROOT PRIVS at mod_delay.c:1943
2023-04-20 11:09:38,804 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2345842] ip-1-2-3-4.eu-west-1.compute.internal: RELINQUISH PRIVS at mod_delay.c:1946
2023-04-20 11:09:38,819 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2345842] ip-1-2-3-4.eu-west-1.compute.internal: RELINQUISH PRIVS at signals.c:85
2023-04-20 11:09:38,819 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2345842] ip-1-2-3-4.eu-west-1.compute.internal: ProFTPD 1.3.8 standalone mode SHUTDOWN
2023-04-20 11:09:38,819 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2345842] ip-1-2-3-4.eu-west-1.compute.internal: ROOT PRIVS at signals.c:92
2023-04-20 11:09:38,820 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2345842] ip-1-2-3-4.eu-west-1.compute.internal: deleting existing scoreboard '/maccsbox/proftpd/var/proftpd.scoreboard'
2023-04-20 11:09:38,828 ip-1-2-3-4.eu-west-1.compute.internal proftpd[2345842] ip-1-2-3-4.eu-west-1.compute.internal: RELINQUISH PRIVS at signals.c:94
```

**Comment by Castaglia** [comment]
> mod_aws gets unloaded: mod_dso/0.5: unloading 'mod_aws.c' Why?

This is part of the normal ProFTPD restart/SIGHUP handling.  Dynamically loaded modules are unloaded, since the changed/new configuration might have removed their `LoadModule` directive.

I'm hoping to have some time this weekend to look deeper into this issue.

**Comment by Castaglia** [comment]
I'm able to reproduce this issue locally; I'm currently seeing these logged:
```
2023-c1ff435a2829 proftpd[11764] localhost: received SIGHUP -- master server reparsing configuration file
2023-c1ff435a2829 proftpd[11764] localhost: ROOT PRIVS at mod_aws.c:664
2023-c1ff435a2829 proftpd[11764] localhost: RELINQUISH PRIVS at mod_aws.c:667
2023-c1ff435a2829 proftpd[11764] localhost: mod_dso/0.5: unloading 'mod_aws.c'
2023-c1ff435a2829 proftpd[11764] localhost: -----BEGIN STACK TRACE-----
2023-c1ff435a2829 proftpd[11764] localhost: [0] proftpd: (accepting connections)(+0x2189f) [0x55c5c253f89f]
2023-c1ff435a2829 proftpd[11764] localhost: [1] proftpd: (accepting connections)(+0x2189f) [0x55c5c253f89f]
2023-c1ff435a2829 proftpd[11764] localhost: [2] /usr/local/libexec/mod_aws.so(aws_health_listener_destroy+0x2f) [0x7ff4a94a4bdf]
2023-c1ff435a2829 proftpd[11764] localhost: [3] /usr/local/libexec/mod_aws.so(+0xa60c) [0x7ff4a94a360c]
2023-c1ff435a2829 proftpd[11764] localhost: [4] proftpd: (accepting connections)(pr_event_generate+0x140) [0x55c5c257b3c0]
```
So I'll hopefully soon track down the cause, and have a fix.

**Comment by Castaglia** [comment]
Using `gdb` to get a closer look:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555577b3a in destroy_pool (p=0x91) at pool.c:597
597	  if (p->parent != NULL) {
(gdb) bt
#0  0x0000555555577b3a in destroy_pool (p=0x91) at pool.c:597
#1  0x00005555555933d7 in pr_inet_close (p=0x300000006, c=0x5555556ad540)
    at inet.c:687
#2  0x00007ffff7d636b4 in aws_health_listener_destroy (p=0x5555556d0ce0, 
    health=0x5555556af4d8) at health.c:529
#3  0x00007ffff7d6025e in aws_mod_unload_ev (event_data=0x7fffffffe030, 
    user_data=0x0) at mod_aws.c:1340
#4  0x00005555555cb77c in pr_event_generate (
    event=0x55555565a3d4 "core.module-unload", event_data=0x7fffffffe030)
    at event.c:371
```

**Comment by Castaglia** [comment]
@3dw1n This should now be fixed in master.  Thanks for reporting this issue!

**Comment by 3dw1n** [comment]
@Castaglia Thanks for looking into this!

In trace.log I do see mod_aws restarting/reloading (see log below) and the ftp server does seem to work again after kill -HUP but the health check still doesn't work after reload and from what I can see in the trace.log othher mod_aws functionality doesn't get started also.

on startup with `Trace event:99 aws:99 aws.error:99 aws.http:99 aws.instance:99` in config I see the following in trace.log:

```
2023-04-24 07:57:25,228 [115401] <event:3>: module 'aws' (0x7f20214e4840) registering handler for event 'core.module-unload' (at 0x7f20214d1630)
2023-04-24 07:57:25,228 [115401] <event:3>: module 'aws' (0x7f20214e4840) registering handler for event 'core.restart' (at 0x7f20214d14b0)
2023-04-24 07:57:25,228 [115401] <event:3>: module 'aws' (0x7f20214e4840) registering handler for event 'core.shutdown' (at 0x7f20214cef40)
2023-04-24 07:57:25,228 [115401] <event:3>: module 'aws' (0x7f20214e4840) registering handler for event 'core.startup' (at 0x7f20214d1cc0)
2023-04-24 07:57:25,233 [115401] <event:8>: dispatching event 'core.postparse' to mod_ctrls (at 0x49e3c0, use cache = false)
2023-04-24 07:57:25,250 [115401] <event:8>: dispatching event 'core.postparse' to mod_delay (at 0x496700, use cache = false)
2023-04-24 07:57:25,251 [115401] <event:8>: dispatching event 'core.postparse' to mod_log (at 0x492010, use cache = false)
2023-04-24 07:57:25,255 [115401] <event:8>: dispatching event 'core.postparse' to mod_rlimit (at 0x47e2a0, use cache = false)
2023-04-24 07:57:25,255 [115401] <event:8>: dispatching event 'core.postparse' to mod_core (at 0x466150, use cache = false)
2023-04-24 07:57:25,293 [115401] <event:8>: dispatching event 'core.startup' to mod_aws (at 0x7f20214d1cc0, use cache = false)
2023-04-24 07:57:25,298 [115401] <aws:8>: listening for AWSHealthCheck http://172.20.200.90:1234/health
2023-04-24 07:57:25,298 [115401] <aws.http:15>: [debug] INFO:   Trying 169.254.169.254:80...
2023-04-24 07:57:25,298 [115401] <aws.http:15>: [debug] INFO: Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
2023-04-24 07:57:25,298 [115401] <aws.http:15>: [debug] HEADER OUT: GET /latest/meta-data/services/domain HTTP/1.1^M
Host: 169.254.169.254^M
Accept: */*^M
 (86 bytes)
....
```
So you see mod_aws starting registering it's event handlers and then starting the listener andd then (not shown in log above) you see the aws api calls.

After sending kill -HUP you do see mod_aws registering it's event handlers but then it seems to stop, no  `<aws:8>: listening for AWSHealthCheck http://172.20.200.90:1234/health` and no logging of the aws api calls:

```
2023-04-24 07:57:36,334 [115401] <event:8>: dispatching event 'core.restart' to mod_aws (at 0x7f20214d14b0, use cache = false)
2023-04-24 07:57:36,343 [115401] <event:8>: dispatching event 'core.restart' to mod_ctrls (at 0x49e950, use cache = false)
2023-04-24 07:57:36,343 [115401] <event:8>: dispatching event 'core.restart' to mod_dso (at 0x49c1b0, use cache = false)
2023-04-24 07:57:36,343 [115401] <event:8>: dispatching event 'core.module-unload' to mod_aws (at 0x7f20214d1630, use cache = false)
2023-04-24 07:57:36,343 [115401] <event:3>: module 'aws' (0x7f20214e4840) unregistering handler for event '(all)'
2023-04-24 07:57:36,343 [115401] <event:3>: module 'aws' (0x7f20214e4840) unregistering handler for event '(all)'
2023-04-24 07:57:36,344 [115401] <event:8>: dispatching event 'core.restart' to mod_delay (at 0x494a50, use cache = false)
2023-04-24 07:57:36,344 [115401] <event:8>: dispatching event 'core.restart' to mod_log (at 0x492420, use cache = false)
2023-04-24 07:57:36,344 [115401] <event:8>: dispatching event 'core.restart' to mod_core (at 0x473220, use cache = false)
2023-04-24 07:57:36,376 [115401] <event:3>: module 'aws' (0x7f20214e4840) registering handler for event 'core.module-unload' (at 0x7f20214d1630)
2023-04-24 07:57:36,376 [115401] <event:3>: module 'aws' (0x7f20214e4840) registering handler for event 'core.restart' (at 0x7f20214d14b0)
2023-04-24 07:57:36,376 [115401] <event:3>: module 'aws' (0x7f20214e4840) registering handler for event 'core.shutdown' (at 0x7f20214cef40)
2023-04-24 07:57:36,376 [115401] <event:3>: module 'aws' (0x7f20214e4840) registering handler for event 'core.startup' (at 0x7f20214d1cc0)
2023-04-24 07:57:36,378 [115401] <event:8>: dispatching event 'core.postparse' to mod_ctrls (at 0x49e3c0, use cache = false)
2023-04-24 07:57:36,392 [115401] <event:8>: dispatching event 'core.postparse' to mod_delay (at 0x496700, use cache = false)
2023-04-24 07:57:36,393 [115401] <event:8>: dispatching event 'core.postparse' to mod_log (at 0x492010, use cache = false)
2023-04-24 07:57:36,394 [115401] <event:8>: dispatching event 'core.postparse' to mod_rlimit (at 0x47e2a0, use cache = false)
2023-04-24 07:57:36,394 [115401] <event:8>: dispatching event 'core.postparse' to mod_core (at 0x466150, use cache = false)
```

I did a make distclean in my proftpd-1.3.8 sourcetree and copied the new mod_aws master over the existing mod_aws files in my local source tree.

**Comment by 3dw1n** [comment]
I don't know if I should open a new issue or if you can reopen this one because I think the issue isn't resolved.

With everything as above except healthcheck disabled and a MasqueradeAddress in the config:

```
ServerType          standalone
UseIPv6             off
PidFile             /testing/proftpd/var/proftpd-%{env:MB_FTPHOST}.pid
Port                21
DefaultServer       on

LoadModule          mod_aws.c

AWSEngine           on
AWSLog              /testing/proftpd/var/log/aws-%{env:MB_FTPHOST}.log
AWSAdjustments      MasqueradeAddress
#AWSHealthCheck      "/health" %{env:HOSTNAME} 1234

PassivePorts          60000 65534
Umask                 002
RootLogin             off
DefaultRoot           ~
RequireValidShell     off
User                  nobody
Group                 nobody
AuthOrder             mod_auth_file.c
AuthGroupFile         /testing/proftpd/etc/proftpd.group id 2000-4000 name ^testing$
AuthUserFile          /testing/proftpd/etc/proftpd.passwd home ^/testing/ftproot/
```

When I connect to the ftp-server I get a correct pasv-response:

```
...
13:32:40	Command:	PASV
13:32:40	Response:	227 Entering Passive Mode (XX,XX,XX,XX,252,51).
13:32:40	Command:	LIST -a
13:32:41	Response:	150 Opening BINARY mode data connection for file list
13:32:41	Response:	226 Transfer complete
...
```

After I do a killall -HUP proftpd to reload the config I get:

```
...
13:33:17	Command:	PASV
13:33:17	Response:	227 Entering Passive Mode (10,0,200,97,253,81).
13:33:17	Status:	Server sent passive reply with unroutable address. Using server address instead.
13:33:17	Command:	LIST -a
13:33:17	Response:	150 Opening BINARY mode data connection for file list
13:33:17	Response:	226 Transfer complete
...
```

When I test with the above and healtcheck also enabled after the killall -HUP proftpd the healthcheck listening port is gone:

```
# netstat -antp |grep 1234
tcp        0      0 10.0.200.97:1234        0.0.0.0:*               LISTEN      1166234/proftpd: (a
# killall -HUP proftpd
# netstat -antp |grep 1234
# telnet 10.0.200.97 1234
Trying 10.0.200.97...
telnet: connect to address 10.0.200.97: Connection refused
```

It's almost as if mod_aws doesn't get reloaded after a killall -HUP.

**Comment by Castaglia** [comment]
Hmm.  I'll take a look; it could be that there's something else that needs to be addressed as well.

**Comment by Castaglia** [comment]
I uncovered some more issues in this area, yes --  hopefully they are the same ones you're encountering.  https://github.com/Castaglia/proftpd-mod_aws/pull/43 should fix these.  Thanks for keeping an eye on this!

**Comment by Castaglia** [comment]
I've now merged these latest fixes into `master`, if you'd like to pull down the latest sources, and see if they work better for you.

**Comment by 3dw1n** [comment]
Thanks for looking into this again!! I just tried your fixes and now the health check seems to survive a kill -HUP:

```
#kill -HUP 1608224
# netstat -antp|grep 1234
tcp        0      0 10.0.200.97:1234        0.0.0.0:*               LISTEN      1608224/proftpd: (a
```

But I still get an incorrect IP in the PASV response after the kill -HUP:

```
**BEFORE KILL -HUP**
06:33:05	Command:	PASV
06:33:05	Response:	227 Entering Passive Mode (54,78,104,44,255,44).
06:33:05	Command:	LIST -a
06:33:05	Response:	150 Opening BINARY mode data connection for file list
06:33:05	Response:	226 Transfer complete

**AFTER KILL -HUP**
06:33:31	Command:	PASV
06:33:31	Response:	227 Entering Passive Mode (10,0,200,97,249,53).
06:33:31	Status:	Server sent passive reply with unroutable address. Using server address instead.
06:33:31	Command:	LIST -a
```

So the health listener seems to survive but other mod_aws settings do not survive the kill -HUP.

Is there anything else I can test? Will dive into the mod_aws documentation to see if there's anything else I can test.

**UPDATE** 
with MasqueradeAddress     127.0.0.1 in global config as below I get the same results but with the configured ip 127.0.0.1. So first connect I get correct external PASV IP in the response and after kill -HUP I get 127.0.0.1:

```
**FIRST CONNECTION:**
06:46:22	Command:	PASV
06:46:22	Response:	227 Entering Passive Mode (XX,XX,XX,XX,251,60).
06:46:22	Command:	LIST -a
06:46:22	Response:	150 Opening BINARY mode data connection for file list
06:46:22	Response:	226 Transfer complete

**AFTER KILL -HUP**
06:46:35	Command:	PASV
06:46:35	Response:	227 Entering Passive Mode (127,0,0,1,243,92).
06:46:35	Status:	Server sent passive reply with unroutable address. Using server address instead.
06:46:35	Command:	LIST -a
```

```
ServerType          standalone
UseIPv6             off
PidFile             /maccsbox/proftpd/var/proftpd-ftp-02.pid
Port                21
DefaultServer       on

TraceLog            /maccsbox/proftpd/var/log/trace.log
Trace               event:99 aws:99 aws.error:99 aws.http:99 aws.instance:99
#LoadModule          mod_aws.c

LoadModule          mod_aws.c

AWSEngine           on
AWSLog              /maccsbox/proftpd/var/log/aws-ftp-02.log
AWSAdjustments      MasqueradeAddress
AWSHealthCheck      "/health" %{env:HOSTNAME} 1234

<Global>
    MasqueradeAddress     127.0.0.1
    PassivePorts          60000 65534
    Umask                 002
    RootLogin             off
    DefaultRoot           ~
    RequireValidShell     off
    User                  nobody
    Group                 nobody
    AuthOrder             mod_auth_file.c
    AuthGroupFile         /maccsbox/proftpd/etc/proftpd.group id 2000-4000 name ^MACCSBOX$
    AuthUserFile          /maccsbox/proftpd/etc/proftpd.passwd home ^/maccsbox/ftproot/
    ExtendedLog           /maccsbox/proftpd/var/log/extended.log
    SystemLog             /maccsbox/proftpd/var/log/system.log
</Global>
```

**Comment by Castaglia** [comment]
I just merged a few more changes into `master`, if you'd like to try them out?  Thanks!

**Comment by 3dw1n** [comment]
--edited-- was too quick, not awake yet and in a hurry to get away for the weekend... bugged me so retested.

It seems to work now, healthcheck still working and now correct masq IP after (mutiple) kill -HUP. Also now I see the output of log_instance_info in the logfile each time I do a kill -HUP!

I'm afraid I really have to get away for the weekend now, will do more testing next week! Thanks and have a nice weekend!!

**Comment by Castaglia** [comment]
Excellent, glad to hear it's working properly for you now!

**Comment by 3dw1n** [comment]
Sorry for bothering you again but I think there might be a little copy/paste error when code was moved to the reparse function.

the code checking if there should be a health listener and if there's a listener address configured in the conf file should be above the code checking if there should be a health listener without an address configured in the conf file and then using the public or local ip of the instance, as it is now it always uses the public/local ip of the instance instead of the configured address.

So I think the code at 1443-1452:
```
  /* If we should be listening for health checks, AND we have already been
   * given an explicit AWSHealthCheck address, then start our listener here.
   * Otherwise, we will wait until we have the EC2 instance' public IPv4
   * address.
   */
  if (aws_use_health == TRUE &&
      aws_health_addr != NULL) {
    (void) aws_health_listening(aws_pool, aws_health_addr, aws_health_port,
      aws_health_uri);
  }
```
should be above the code now at 1415-1441:
```
  if (aws_use_health == TRUE &&
      instance_health == NULL) {
    const char *addr = NULL;

    /* Use the public IPv4 address, if we have one.  If not, fall back to
     * the local/private IPv4 address.
     */
    if (instance_info->public_ipv4 != NULL) {
      addr = pstrndup(aws_pool, instance_info->public_ipv4,
        instance_info->public_ipv4sz);

    } else if (instance_info->local_ipv4 != NULL) {
      addr = pstrndup(aws_pool, instance_info->local_ipv4,
        instance_info->local_ipv4sz);
    }

    aws_health_addr = addr;

    if (aws_health_addr != NULL) {
      (void) aws_health_listening(aws_pool, aws_health_addr, aws_health_port,
        aws_health_uri);

    } else {
      (void) pr_log_writefile(aws_logfd, MOD_AWS_VERSION,
        "unable to listen for AWSHealthCheck: unable to discover address");
    }
  }
```

Even with this fix proftpd doesn't accept new connections when there is an active connection to the healthcheck and you do a kill -HUP, it generates a stack trace when there is a connection to the health port and you do a kill -HUP:

```
2023-08-15 09:39:06,393 proftpd[3837441] 10.0.200.97: -----BEGIN STACK TRACE-----
2023-08-15 09:39:06,394 proftpd[3837441] 10.0.200.97: [0] /proftpd-1.3.8/libexec/mod_aws.so(+0xa781) [0x7f233b64b781]
2023-08-15 09:39:06,394 proftpd[3837441] 10.0.200.97: [1] /proftpd-1.3.8/libexec/mod_aws.so(+0xa781) [0x7f233b64b781]
2023-08-15 09:39:06,394 proftpd[3837441] 10.0.200.97: [2] proftpd: (accepting connections)(handle_alarm+0x262) [0x419122]
2023-08-15 09:39:06,394 proftpd[3837441] 10.0.200.97: [3] proftpd: (accepting connections)(pr_signals_handle+0x42f) [0x42664f]
2023-08-15 09:39:06,394 proftpd[3837441] 10.0.200.97: [4] proftpd: (accepting connections)(pr_signals_unblock+0x5a) [0x42759a]
2023-08-15 09:39:06,394 proftpd[3837441] 10.0.200.97: [5] proftpd: (accepting connections)(pr_timer_usleep+0x4e) [0x4199ce]
2023-08-15 09:39:06,394 proftpd[3837441] 10.0.200.97: [6] proftpd: (accepting connections)(pr_signals_handle+0x4ca) [0x4266ea]
2023-08-15 09:39:06,394 proftpd[3837441] 10.0.200.97: [7] proftpd: (accepting connections)() [0x41758b]
2023-08-15 09:39:06,394 proftpd[3837441] 10.0.200.97: [8] proftpd: (accepting connections)(main+0x530) [0x4155e0]
2023-08-15 09:39:06,394 proftpd[3837441] 10.0.200.97: [9] /lib64/libc.so.6(+0x3feb0) [0x7f233b83feb0]
2023-08-15 09:39:06,395 proftpd[3837441] 10.0.200.97: [10] /lib64/libc.so.6(__libc_start_main+0x80) [0x7f233b83ff60]
2023-08-15 09:39:06,395 proftpd[3837441] 10.0.200.97: [11] proftpd: (accepting connections)(_start+0x25) [0x415b55]
2023-08-15 09:39:06,395 proftpd[3837441] 10.0.200.97: -----END STACK TRACE-----

```

**Comment by Castaglia** [comment]
@3dw1n Thanks for the follow-up.  You are indeed correct about the copy/paste error, and the ordering of operations there.

In addition, I reproduced the stacktrace error, and I believe I have fixed its cause as well, with the latest commits to `master`.

**Comment by 3dw1n** [comment]
I think we're getting there Castaglia, but I'm afraid there's still a strack trace. What I did was start the ftpd, test the healthcheck with `wget http://10.0.200.97:1234/health` then `killall -HUP proftpd`, tested health again with wget and was still working, kill -HUP again test again etc.. a couple of times and no problem also connecting to ftp was still working but when I do a `telnet 10.0.200.97 1234` and then immediately (when the telnet is still connected to the health port) a kill -HUP then I get the strack trace:

```
2023-08-16 05:52:39,760 proftpd[183623] 10.0.200.97: received SIGHUP -- master server reparsing configuration file
2023-08-16 05:52:39,904 proftpd[183623] 10.0.200.97: -----BEGIN STACK TRACE-----
2023-08-16 05:52:39,904 proftpd[183623] 10.0.200.97: [0] /proftpd-1.3.8/libexec/mod_aws.so(+0xa6f9) [0x7fd7fa2336f9]
2023-08-16 05:52:39,904 proftpd[183623] 10.0.200.97: [1] /proftpd-1.3.8/libexec/mod_aws.so(+0xa6f9) [0x7fd7fa2336f9]
2023-08-16 05:52:39,904 proftpd[183623] 10.0.200.97: [2] proftpd: (accepting connections)(handle_alarm+0x262) [0x419122]
2023-08-16 05:52:39,904 proftpd[183623] 10.0.200.97: [3] proftpd: (accepting connections)(pr_signals_handle+0x42f) [0x42664f]
2023-08-16 05:52:39,904 proftpd[183623] 10.0.200.97: [4] proftpd: (accepting connections)(pr_signals_unblock+0x5a) [0x42759a]
2023-08-16 05:52:39,904 proftpd[183623] 10.0.200.97: [5] proftpd: (accepting connections)(pr_timer_usleep+0x4e) [0x4199ce]
2023-08-16 05:52:39,904 proftpd[183623] 10.0.200.97: [6] proftpd: (accepting connections)(pr_signals_handle+0x4ca) [0x4266ea]
2023-08-16 05:52:39,904 proftpd[183623] 10.0.200.97: [7] proftpd: (accepting connections)() [0x41758b]
2023-08-16 05:52:39,904 proftpd[183623] 10.0.200.97: [8] proftpd: (accepting connections)(main+0x530) [0x4155e0]
2023-08-16 05:52:39,904 proftpd[183623] 10.0.200.97: [9] /lib64/libc.so.6(+0x3feb0) [0x7fd7fa03feb0]
2023-08-16 05:52:39,904 proftpd[183623] 10.0.200.97: [10] /lib64/libc.so.6(__libc_start_main+0x80) [0x7fd7fa03ff60]
2023-08-16 05:52:39,904 proftpd[183623] 10.0.200.97: [11] proftpd: (accepting connections)(_start+0x25) [0x415b55]
2023-08-16 05:52:39,904 proftpd[183623] 10.0.200.97: -----END STACK TRACE-----
2023-08-16 05:52:39,904 proftpd[183623] 10.0.200.97: ProFTPD terminating (signal 11)
2023-08-16 05:52:39,915 proftpd[183623] 10.0.200.97: ProFTPD 1.3.8 standalone mode SHUTDOWN
```

Thanks a lot again for helping me out here!! I really like this to work as I use the kill -HUP to reload the config from a cronjob checking if a new certificate was issued forcing it to get used by the ftpd with the reload config.

**Comment by Castaglia** [comment]
Right.  The use of `telnet`, without actually sending the HTTP request, is also how I was testing locally -- and with the latest source code, I didn't see the stacktraces anymore.  But I'll try again.

**Comment by 3dw1n** [comment]
To be sure I just refreshed health.c and mod_aws.c and did a make/make install again. I start the ftpd, do a telnet then immediately a kill -HUP and do a telnet again and immediately a kill -HUP then I get the stack trace:

```
2023-08-17 05:10:32,758 proftpd[1908599] 10.0.200.97: forked daemon process (PID 1908601)
2023-08-17 05:10:32,772 proftpd[1908601] 10.0.200.97: ProFTPD 1.3.8 (stable) (built Tue Aug 8 2023 11:31:30 UTC) standalone mode STARTUP
2023-08-17 05:10:42,853 proftpd[1908601] 10.0.200.97: received SIGHUP -- master server reparsing configuration file
2023-08-17 05:10:54,085 proftpd[1908601] 10.0.200.97: received SIGHUP -- master server reparsing configuration file
2023-08-17 05:10:54,260 proftpd[1908601] 10.0.200.97: -----BEGIN STACK TRACE-----
2023-08-17 05:10:54,260 proftpd[1908601] 10.0.200.97: [0] /proftpd-1.3.8/libexec/mod_aws.so(+0xa6f9) [0x7f523702a6f9]
2023-08-17 05:10:54,260 proftpd[1908601] 10.0.200.97: [1] /proftpd-1.3.8/libexec/mod_aws.so(+0xa6f9) [0x7f523702a6f9]
2023-08-17 05:10:54,260 proftpd[1908601] 10.0.200.97: [2] proftpd: (accepting connections)(handle_alarm+0x262) [0x419122]
2023-08-17 05:10:54,260 proftpd[1908601] 10.0.200.97: [3] proftpd: (accepting connections)(pr_signals_handle+0x42f) [0x42664f]
2023-08-17 05:10:54,260 proftpd[1908601] 10.0.200.97: [4] proftpd: (accepting connections)(pr_signals_unblock+0x5a) [0x42759a]
2023-08-17 05:10:54,260 proftpd[1908601] 10.0.200.97: [5] proftpd: (accepting connections)(pr_timer_usleep+0x4e) [0x4199ce]
2023-08-17 05:10:54,260 proftpd[1908601] 10.0.200.97: [6] proftpd: (accepting connections)(pr_signals_handle+0x4ca) [0x4266ea]
2023-08-17 05:10:54,260 proftpd[1908601] 10.0.200.97: [7] proftpd: (accepting connections)() [0x41758b]
2023-08-17 05:10:54,260 proftpd[1908601] 10.0.200.97: [8] proftpd: (accepting connections)(main+0x530) [0x4155e0]
2023-08-17 05:10:54,260 proftpd[1908601] 10.0.200.97: [9] /lib64/libc.so.6(+0x3feb0) [0x7f5236e3feb0]
2023-08-17 05:10:54,260 proftpd[1908601] 10.0.200.97: [10] /lib64/libc.so.6(__libc_start_main+0x80) [0x7f5236e3ff60]
2023-08-17 05:10:54,261 proftpd[1908601] 10.0.200.97: [11] proftpd: (accepting connections)(_start+0x25) [0x415b55]
2023-08-17 05:10:54,261 proftpd[1908601] 10.0.200.97: -----END STACK TRACE-----
2023-08-17 05:10:54,261 proftpd[1908601] 10.0.200.97: ProFTPD terminating (signal 11)
2023-08-17 05:10:54,275 proftpd[1908601] 10.0.200.97: ProFTPD 1.3.8 standalone mode SHUTDOWN
```

**Comment by Castaglia** [comment]
I think I understand how these segfaults (attempts to reference a null pointer) are occurring.  I'm not sure yet how to rework the code to deal with this situation, but knowing the problem is the first step.

**Comment by Castaglia** [comment]
OK, I've just committed some changes which, for my local testing, are handling the scenario of SIGHUP while handling a healthcheck request much better.  Hopefully it'll work better in your setup/testing a well?

**Comment by 3dw1n** [comment]
Kill -HUP doesn't force stacktraces anymore no matter how hard I try :-) but it doesn't kill the telnet connection anymore and as long as telnet is connected ftp-client connections to the ftp-server stall, the ftp-client connection continues as soon as I kill the telnet ( CTLR-]  quit).

**Comment by Castaglia** [comment]
> Kill -HUP doesn't force stacktraces anymore no matter how hard I try :-) but it doesn't kill the telnet connection anymore and as long as telnet is connected ftp-client connections to the ftp-server stall, the ftp-client connection continues as soon as I kill the telnet ( CTLR-] quit).

I've filed https://github.com/Castaglia/proftpd-mod_aws/issues/45 to address this related issue.  Thanks!

**Comment by Castaglia** [comment]
@3dw1n Per #45, using `telnet` or `nc` for your AWS health check should no longer block the daemon unnecessarily.
